# PostgreSQL Database - dev profile
spring.datasource.url=jdbc:postgresql://localhost:5432/simplewebservice
spring.datasource.username=hernan
spring.datasource.password=password

# Keep schema between application restarts
spring.jpa.hibernate.ddl-auto=update

# Optional: H2 console is not needed when using PostgreSQL
spring.h2.console.enabled=false