package com.hmeclazcke.simplewebservicetest.exception;

public enum ErrorCode {
    INVALID_REQUEST,
    INVALID_ACCOUNT,
    ACCOUNT_HOLDER_REQUIRED,
    INITIAL_BALANCE_REQUIRED,
    INITIAL_BALANCE_NEGATIVE,
    ACCOUNT_NOT_FOUND,
    INVALID_TRANSFER,
    TRANSFER_ACCOUNTS_REQUIRED,
    TRANSFER_ACCOUNTS_SAME,
    TRANSFER_AMOUNT_REQUIRED,
    TRANSFER_AMOUNT_NOT_POSITIVE,
    TRANSFER_NOT_FOUND,
    INSUFFICIENT_FUNDS
}
